#pragma once


enum
{
    EVT_APP_TICK = 1,
    EVT_EC_FAILED,
    EVT_DISK_INSERTED,
    EVT_DISK_EJECTED,
    EVT_DISK_ERROR,

    EVT_SETTING_CLICKED,
    EVT_BACK_CLICKED,

    EVT_SETTINGS_CLOSED,
    
    EVT_BROWSER_UI_UPDATE,
    EVT_BROWSER_PLAY_CLICKED,
    EVT_BROWSER_SETTING_CLOSED,

    EVT_EARPIECE_PLUGGED,
    EVT_EARPIECE_UNPLUGGED,

    EVT_PLAYER_UI_UPDATE,
    EVT_PLAYER_GENERAL_TIMER,
    EVT_PLAYER_PLAY_CLICKED,
    EVT_PLAYER_UP_CLICKED,
    EVT_PLAYER_DOWN_CLICKED,
    EVT_PLAYER_SETTING_CLICKED,
    EVT_PLAYER_BACK_CLICKED,
    EVT_PLAYER_PLAY_SONG,
    EVT_PLAYER_PLAY_NEXT,
    EVT_PLAYER_SONG_ENDED,
};
